name: forwarder
version: '1.1'
summary: forwarder server
description: forwarder server
confinement: strict
base: core20

parts:
  forwarder:
    plugin: rust
    source: .

apps:
  forwarderd:
    daemon: simple
    command: bin/forwarder --addr 0.0.0.0:4141 --zero 127.0.0.1:4142
    stop-timeout: 1s
    stop-mode: sigterm
    install-mode: enable
    plugs:
      - network-bind
      - process-control
      - cpu-control
