name: forwarder
version: '1.0'
summary: forwarder server
description: forwarder server
confinement: strict
base: core18

parts:
  forwarder:
    plugin: rust
    source: git@github.com:itsabgr/forwarder.git
    source-type: git

apps:
  forwarderd:
    daemon: simple
    command: bin/forwarder --addr 0.0.0.0:6666 --def 127.0.0.1:6665
    stop-timeout: 1s
    stop-mode: sigterm
    install-mode: enable
    plugs:
      - network-bind
